# test_ai.py
from app.ai_client import generate_questions

def test_ai():
    resume_text = """
    John Doe is a software engineer with 5 years of experience in Python, JavaScript, and cloud technologies.
    Worked on web applications, APIs, and machine learning models.
    """
    skills = "Python, JavaScript, Cloud"
    role = "Software Engineer"
    years = "5"

    try:
        questions = generate_questions(resume_text, role=role, skills=skills, years=years)
        print("Questions generated by DeepSeek R1 0528:\n")
        for i, q in enumerate(questions, 1):
            print(f"{i}. {q}")
        print("\nAI test successful!")
    except Exception as e:
        print(f"AI test failed: {e}")

if __name__ == "__main__":
    test_ai()

